site_name: Wiring Specialties - CT
nav:
    - General: index.md
    - Home: home.md
    - Category: category.md
    - Product: product.md
    - Static: static.md
    - Mega Menu: menu.md
    - Other: other.md
theme: readthedocs
extra_css:
  - style.css
